spring:
  application:
    name: Dynamic-Email-Generator

server:
  port: 8443
  # needed for nginx header forwarding
  forward-headers-strategy: framework

  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: api
    protocol: TLS
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
    # one-way TLS
    client-auth: none