name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: target/email-generator.jar
  build_docker:
    runs-on: ubuntu-latest
    needs: build_maven
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts
          path: target/

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag email-generator-service:$(date +%s)

      - name: Generate self-signed certificates for reverse proxy
        run: |
          mkdir -p nginx/certs
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx/certs/nginx.key -out nginx/certs/nginx.crt -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.localhost.com"
      - name: Generate keystore for the Spring Boot service
        run: |
          mkdir -p tls/keystore
          keytool -genkeypair -alias api \
          -keyalg RSA -keysize 2048 \
          -storetype PKCS12 \
          -keystore tls/keystore/springboot.p12 \
          -validity 365 \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=www.localhost.com, OU=Denial, O=Dis, L=Springfield, S=Denial, C=US"

      - name: Run Docker Compose
        run: docker-compose --env-file ./.dev-env up -d
      - name: Sleep to allow service to start
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Call API Endpoint
        run: |
          curl -k -X GET \
            "https://localhost:9443/app/v1/email/generate?expression=first(str1,1);raw(.);lit(str2);raw(@gmail.com)&str1=Ivan&str2=Petrov&str2=Ivanov"
      - name: Sleep to allow api request processing
        uses: jakejarvis/wait-action@master
        with:
          time: '2'
      - name: Check running containers
        run: docker ps -a
      - name: Check service logs
        run: docker logs dynamic-email-generator_email-generator-service_1
      - name: Check nginx logs
        run: docker logs dynamic-email-generator_nginx_1