name: Docker Compose Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  docker_compose_test:
    runs-on: ubuntu-latest
    needs: [setup, build_maven]
    steps:
      - uses: actions/checkout@v4
      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.yml up --build --detach
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down