name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  build_docker:
     runs-on: ubuntu-latest
     needs: build_maven
     steps:
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag email-generator-service:$(date +%s)
